name: Test

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Check migrations file
        run: chmod +x ./.github/scripts/ckeck-migrations-file.sh && ./.github/scripts/ckeck-migrations-file.sh
        shell: sh

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore 

      - name: Run unit tests
        run: dotnet test ./Meetups.Tests --no-build --verbosity normal